feat(ui5-ainotice): introduce new component
UI5/webcomponents pull request #10169
Opened 2024-11-12 08:32 UTC by StefanDimitrov04

2024-11-13 14:07 UTC, ilhan007 commented on packages/main/src/AINotice.ts
> +	tag: "ui5-ainotice",
I think `ui5-ai-notice` would be better. Also, I think this component belongs to the "ai" package. If you move it to the "ai" package.

2024-11-13 14:08 UTC, ilhan007 commented on packages/main/src/AINotice.ts
> +class AINotice extends UI5Element {
If  we move the component in the "ai" package, we call it just "Notice", not "AINotice" since all components in the "ai" package are ai things

2024-11-13 14:09 UTC, ilhan007 commented on packages/main/src/AINotice.ts
> + * @since 2.4.0
2.4.0 is released, 2.5.0 is coming in Dec (1st to 5th)

2024-11-13 14:12 UTC, ilhan007 commented on packages/main/src/AINotice.ts
> +	popup!: HTMLElement;
The slots are array by nature, users can slot multiple elements inside, even if the component works and expects a single popup. Thus, the proper TS type would be

popup!: Array<HTMLElement>;

2024-11-13 14:12 UTC, ilhan007 commented on packages/main/src/AINotice.ts
> +		const attributionText = this.shadowRoot?.querySelector(".link-text") as HTMLElement;
querySelector is generic, we can make use of it:

don't
this.shadowRoot?.querySelector<HTMLElement>(".link-text") as HTMLElement;

do
this.shadowRoot?.querySelector<HTMLElement>(".link-text");

2024-11-13 14:15 UTC, ilhan007 commented on packages/main/src/AINotice.ts
> +import Popover from "./Popover.js";
you don't depend on the Popover - it's not used in the template. In the class it's only used as a type, so import it as a type - `import type Popover...`

2024-11-13 14:17 UTC, ilhan007 commented on packages/main/src/AINotice.ts
> +	onPress(e: Event) {
I don't get why we open this popover. It's pretty easy for developers to open it.
We only need to provide an event, and they can execute this on their side.

```ts
	popup.opener = e.target as HTMLElement;
	popup.open = true;
```

This way, the entire popup slot also will become obsolete.
Is there a specific reason to have a popup slot?

2024-11-13 14:18 UTC, ilhan007 commented on packages/main/src/themes/AINotice.css
> +.verificationText {
we have convention for class names in css - look some of the existing compoenents

2024-11-13 14:22 UTC, ilhan007 commented on packages/main/cypress/specs/AINotice.cy.ts
> +		cy.mount("<ui5-ainotice attribution-text='Test Attribution' verification-text='Test Verification'> <ui5-popover header-text='Opened Popover' slot='popup'></ui5-ainotice>");
I don't see an assertion in this test ("should handle click event and trigger onPress function.") or it verifies that some elements are clicked successfully, found by cypress, and the test does not fail.

2024-11-13 14:22 UTC, ilhan007 commented on packages/main/src/AINotice.hbs
> +<div class="ainotice">
all class names should be changed - see some existing components for the conventions

2024-11-13 14:24 UTC, ilhan007 commented on packages/main/cypress/specs/AINotice.cy.ts
> +		cy.mount("<ui5-ainotice attribution-text='Test Attribution' verification-text='Test Verification' show-icon='false'></ui5-ainotice>");
show-icon='false' is actually truthy. if you want to test that show-icon is false, you must not sett the attribute at all

2024-11-13 14:29 UTC, ilhan007 commented on packages/main/cypress/specs/AINotice.cy.ts
> +import "../../../icons/src/AllIcons.js";
You don't need the allIcons import as you don't have tests that use so many icons.
you only check if some internal links has the "ai" icon.

If you import the "ai" within the Notice component
via
import "@ui5/webcomponents-icons/dist/ai.js";

you won't need this import at all.

2024-11-13 14:30 UTC, ilhan007 requested changes
There are some points for improvements - posted inline.

2024-11-18 07:55 UTC, elenastoyanovaa requested changes

2024-12-22 00:32 UTC, closed without merging