feat(ui5-date-*): adapt date and time controls to timezone feature
UI5/webcomponents pull request #8577
Opened 2024-03-29 09:04 UTC by tsanislavgatev

Adapting the date and time controls to the timezone feature, allowing the controls to present date in different timezones.

Adaptation is done by using the UI5Date object provided by ui5.

Can be tested either via  html tag:

```html
<script data-ui5-config type="application/json">
	{
		"language": "EN",
		"timezone" : "Pacific/Apia"
	}
</script>
```
or by adding a query parameter to the url: `?sap-ui-timezone=XXXX`

The timezone identifiers format is the one used in IANA timezone database.

2024-04-02 12:14 UTC, BorisDafov requested changes

2024-04-02 12:14 UTC, BorisDafov commented on packages/website/docs/_components_pages/main/TimePicker.mdx
> +You can set to the configuration the preferred timezone, such as: Asia/Tokyo, Pacific/Apia, Asia/Kolkata, Europe/Sofia and etc.
time zone

2024-04-02 12:14 UTC, BorisDafov commented on packages/website/docs/_samples/main/Calendar/CalendarInDifferentTimezone/sample.html
> +    <title>Calendar in different time zone</title>
Title case:
Calendar in Different Time Zone

2024-04-02 12:14 UTC, BorisDafov commented on packages/website/docs/_samples/main/DatePicker/DatePickerInDifferentTimezone/sample.html
> +    <title>DatePicker in different time zone</title>
DatePicker in Different Time Zone

2024-04-02 12:14 UTC, BorisDafov commented on packages/website/docs/_samples/main/DateTimePicker/DateTimePickerInDifferentTimezone/sample.html
> +    <title>DateTimePicker in different time zone</title>
DateTimePicker in Different Time Zone

2024-04-02 12:14 UTC, BorisDafov commented on packages/website/docs/_samples/main/TimePicker/TimePickerInDifferentTimezone/sample.html
> +    <title>TimePicker om different time zone</title>
TimePicker in Different Time Zone

2024-04-03 06:38 UTC, closed without merging

2024-04-03 06:38 UTC, tsanislavgatev commented
Mistakenly merged main and not release-2.0. The work will continue in: https://github.com/SAP/ui5-webcomponents/pull/8610