refactor(ui5-li): remove image property and rename imageContent slot
UI5/webcomponents pull request #8690
Opened 2024-04-08 13:46 UTC by yanaminkova

Removes the `image` property  of  the `ui5-li` and renames the `imageContent` slot is renamed to `image`

BREAKING CHANGE: The `image` property of the `ui5-li` is removed and the `imageContent` slot is renamed to `image`.
If you have previously used the `image` property:
```html
<ui5-li image="./img/HT-1022.jpg">Standard List Item</ui5-li>
```
it will no longer work for the component.

If you have previously used the `imageContent` slot:
```html
<ui5-li> Avatar inside imageContent slot
	<div slot="imageContent">
		<ui5-avatar shape="Square" initials="ABC" color-scheme="Accent2"></ui5-avatar>
	</div>
</ui5-li>
```

Now use `image`  instead:
```html
<ui5-li> Avatar inside image slot
	<div slot="image">
		<ui5-avatar shape="Square" initials="ABC" color-scheme="Accent2"></ui5-avatar>
	</div>
</ui5-li>

```

Related to https://github.com/SAP/ui5-webcomponents/issues/8461, https://github.com/SAP/ui5-webcomponents/issues/7887

2024-04-08 15:40 UTC, ilhan007 commented on packages/website/docs/_samples/main/List/GroupHeaders/sample.html
> +        <ui5-li icon="navigation-right-arrow"
At least in the new samples (website/docs/_samples), let's keep the images, it's good to show that after the "image" property is removed, we can get the same thing as before via the "image" slot.

2024-04-08 15:41 UTC, ilhan007 commented on packages/main/test/pages/List.html
> -		<ui5-li image="./img/HT-1000.jpg" icon="navigation-right-arrow" additional-text="Available">Voluptate do eu cupidatat elit est culpa. Reprehenderit eiusmod voluptate ex est dolor nostrud Lorem Lore
At leat in the main test page, we could still show the images.

2024-04-12 09:58 UTC, nnaydenow requested changes

2024-04-12 09:58 UTC, nnaydenow commented on packages/main/src/StandardListItem.ts
>  	 */
Change since tag to 2.0.0 since it's newly introduced API.

2024-04-12 09:58 UTC, nnaydenow commented on packages/main/test/pages/List.html
> +			<div slot="image">
this wrapper div is not needed. You can directly pass the slot attribute to the ui5-avatar. This apply to all other test pages

2024-04-16 08:51 UTC, dobrinyonkov commented
Noticed that the suggestion item is composing the list item and it uses the `image` proeprty and it seems that until it's an abstract item, this change could not be directly consumed there. 
Actually, the InputPopover.hbs renders `ui5-li-suggestion-item`s from either an `ui5-li`'s data or `ui5-suggestion-item`'s data. I'm not sure the image slot can be transfered in such a way to the `ui5-li-suggestion-item` dom. I could be wrong thought.

We can add somehting like this to the InputPopover.hbs:

```hbs
	data-ui5-key="{{key}}"
>
	{{#if this.image}}
		<ui5-avatar shape="Square" slot="image">
			<img src="{{this.image}}"/>
		</ui5-avatar>
	{{/if}}
	{{{ this.text }}}
```

But this will only work for the `ui5-suggestion-item` as for the `ui5-li` this image property will be an array of the slotted nodes (which for some reason is empty array even when we slot an avatar)

2024-05-28 09:34 UTC, closed without merging